import { test, expect } from '@playwright/test'

const SLUG = 'sport-climbing-basics'
const BASE = 'http://localhost:3001'

// Public, shell-using pages. The homepage uses <Header /> + <Footer /> directly
// rather than <MarketingShell />, but the rendered shell is the same. Auth pages
// (/login, /register, /verify-email, …) intentionally keep their bare card layout.
// /account/* and /book/* DO use the shell but require authentication — they're
// covered by tests/e2e/account-shell.spec.ts instead.
const pages = [
  '/',
  '/calendar',
  '/programs',
  `/trips/${SLUG}`,
  `/trips/${SLUG}/dates`,
  `/trips/${SLUG}/faq`,
  `/trips/${SLUG}/logistics`,
]

for (const path of pages) {
  test(`shell renders on ${path}`, async ({ page }) => {
    const res = await page.goto(`${BASE}${path}`)
    expect(res?.status()).toBe(200)
    // Header + footer should both appear via MarketingShell (or the equivalent
    // direct <Header /> / <Footer /> composition on the homepage).
    await expect(page.locator('header').first()).toBeVisible()
    await expect(page.locator('footer').first()).toBeVisible()
  })
}

// Snapshot assertions deliberately omitted: visual baselines are generated by
// a human running `--update-snapshots` once the Figma R2 shell restyle lands.
