import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_programs_blocks_trip_grid_variant" ADD VALUE IF NOT EXISTS 'featureLead';
  ALTER TYPE "public"."enum_programs_blocks_faq_variant" ADD VALUE IF NOT EXISTS 'lightEditorial';
  ALTER TYPE "public"."enum_programs_blocks_guide_grid_variant" ADD VALUE IF NOT EXISTS 'photoOverlay';
  ALTER TYPE "public"."enum_guides_blocks_trip_grid_variant" ADD VALUE IF NOT EXISTS 'featureLead';
  ALTER TYPE "public"."enum_guides_blocks_faq_variant" ADD VALUE IF NOT EXISTS 'lightEditorial';
  ALTER TYPE "public"."enum_guides_blocks_cta_variant" ADD VALUE IF NOT EXISTS 'finalRed';
  ALTER TYPE "public"."enum_locations_blocks_trip_grid_variant" ADD VALUE IF NOT EXISTS 'featureLead';
  ALTER TYPE "public"."enum_locations_blocks_faq_variant" ADD VALUE IF NOT EXISTS 'lightEditorial';
  ALTER TYPE "public"."enum_locations_blocks_guide_grid_variant" ADD VALUE IF NOT EXISTS 'photoOverlay';
  ALTER TYPE "public"."enum_locations_blocks_cta_variant" ADD VALUE IF NOT EXISTS 'finalRed';
  ALTER TYPE "public"."enum_events_blocks_faq_variant" ADD VALUE IF NOT EXISTS 'lightEditorial';
  ALTER TYPE "public"."enum_posts_blocks_trip_grid_variant" ADD VALUE IF NOT EXISTS 'featureLead';
  ALTER TYPE "public"."enum_posts_blocks_program_grid_variant" ADD VALUE IF NOT EXISTS 'darkCompact';
  ALTER TYPE "public"."enum_posts_blocks_location_grid_variant" ADD VALUE IF NOT EXISTS 'countryTiles';
  ALTER TYPE "public"."enum_posts_blocks_guide_grid_variant" ADD VALUE IF NOT EXISTS 'photoOverlay';
  ALTER TYPE "public"."enum_posts_blocks_faq_variant" ADD VALUE IF NOT EXISTS 'lightEditorial';
  ALTER TYPE "public"."enum_posts_blocks_cta_variant" ADD VALUE IF NOT EXISTS 'finalRed';
  ALTER TYPE "public"."enum_pages_blocks_hero_variant" ADD VALUE IF NOT EXISTS 'brandEditorial';
  ALTER TYPE "public"."enum_pages_blocks_stats_variant" ADD VALUE IF NOT EXISTS 'inlineDark';
  ALTER TYPE "public"."enum_pages_blocks_stats_variant" ADD VALUE IF NOT EXISTS 'numberedDark';
  ALTER TYPE "public"."enum_pages_blocks_cta_variant" ADD VALUE IF NOT EXISTS 'finalRed';
  ALTER TYPE "public"."enum_pages_blocks_trip_grid_variant" ADD VALUE IF NOT EXISTS 'featureLead';
  ALTER TYPE "public"."enum_pages_blocks_program_grid_variant" ADD VALUE IF NOT EXISTS 'darkCompact';
  ALTER TYPE "public"."enum_pages_blocks_location_grid_variant" ADD VALUE IF NOT EXISTS 'countryTiles';
  ALTER TYPE "public"."enum_pages_blocks_guide_grid_variant" ADD VALUE IF NOT EXISTS 'photoOverlay';
  ALTER TYPE "public"."enum_pages_blocks_faq_variant" ADD VALUE IF NOT EXISTS 'lightEditorial';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   UPDATE "programs_blocks_trip_grid" SET "variant" = 'editorial' WHERE "variant" = 'featureLead';
  UPDATE "programs_blocks_faq" SET "variant" = 'twoColumn' WHERE "variant" = 'lightEditorial';
  UPDATE "programs_blocks_guide_grid" SET "variant" = 'cards' WHERE "variant" = 'photoOverlay';
  UPDATE "guides_blocks_trip_grid" SET "variant" = 'editorial' WHERE "variant" = 'featureLead';
  UPDATE "guides_blocks_faq" SET "variant" = 'twoColumn' WHERE "variant" = 'lightEditorial';
  UPDATE "guides_blocks_cta" SET "variant" = 'red' WHERE "variant" = 'finalRed';
  UPDATE "locations_blocks_trip_grid" SET "variant" = 'editorial' WHERE "variant" = 'featureLead';
  UPDATE "locations_blocks_faq" SET "variant" = 'twoColumn' WHERE "variant" = 'lightEditorial';
  UPDATE "locations_blocks_guide_grid" SET "variant" = 'cards' WHERE "variant" = 'photoOverlay';
  UPDATE "locations_blocks_cta" SET "variant" = 'red' WHERE "variant" = 'finalRed';
  UPDATE "events_blocks_faq" SET "variant" = 'twoColumn' WHERE "variant" = 'lightEditorial';
  UPDATE "posts_blocks_trip_grid" SET "variant" = 'editorial' WHERE "variant" = 'featureLead';
  UPDATE "posts_blocks_program_grid" SET "variant" = 'compact' WHERE "variant" = 'darkCompact';
  UPDATE "posts_blocks_location_grid" SET "variant" = 'compact' WHERE "variant" = 'countryTiles';
  UPDATE "posts_blocks_guide_grid" SET "variant" = 'cards' WHERE "variant" = 'photoOverlay';
  UPDATE "posts_blocks_faq" SET "variant" = 'twoColumn' WHERE "variant" = 'lightEditorial';
  UPDATE "posts_blocks_cta" SET "variant" = 'red' WHERE "variant" = 'finalRed';
  UPDATE "pages_blocks_hero" SET "variant" = 'editorial' WHERE "variant" = 'brandEditorial';
  UPDATE "pages_blocks_stats" SET "variant" = 'dark' WHERE "variant" IN ('inlineDark', 'numberedDark');
  UPDATE "pages_blocks_cta" SET "variant" = 'red' WHERE "variant" = 'finalRed';
  UPDATE "pages_blocks_trip_grid" SET "variant" = 'editorial' WHERE "variant" = 'featureLead';
  UPDATE "pages_blocks_program_grid" SET "variant" = 'compact' WHERE "variant" = 'darkCompact';
  UPDATE "pages_blocks_location_grid" SET "variant" = 'compact' WHERE "variant" = 'countryTiles';
  UPDATE "pages_blocks_guide_grid" SET "variant" = 'cards' WHERE "variant" = 'photoOverlay';
  UPDATE "pages_blocks_faq" SET "variant" = 'twoColumn' WHERE "variant" = 'lightEditorial';
   ALTER TABLE "programs_blocks_trip_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "programs_blocks_trip_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_programs_blocks_trip_grid_variant";
  CREATE TYPE "public"."enum_programs_blocks_trip_grid_variant" AS ENUM('cards', 'compact', 'editorial');
  ALTER TABLE "programs_blocks_trip_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_programs_blocks_trip_grid_variant";
  ALTER TABLE "programs_blocks_trip_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_programs_blocks_trip_grid_variant" USING "variant"::"public"."enum_programs_blocks_trip_grid_variant";
  ALTER TABLE "programs_blocks_faq" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "programs_blocks_faq" ALTER COLUMN "variant" SET DEFAULT 'twoColumn'::text;
  DROP TYPE "public"."enum_programs_blocks_faq_variant";
  CREATE TYPE "public"."enum_programs_blocks_faq_variant" AS ENUM('twoColumn', 'singleColumn');
  ALTER TABLE "programs_blocks_faq" ALTER COLUMN "variant" SET DEFAULT 'twoColumn'::"public"."enum_programs_blocks_faq_variant";
  ALTER TABLE "programs_blocks_faq" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_programs_blocks_faq_variant" USING "variant"::"public"."enum_programs_blocks_faq_variant";
  ALTER TABLE "programs_blocks_guide_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "programs_blocks_guide_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_programs_blocks_guide_grid_variant";
  CREATE TYPE "public"."enum_programs_blocks_guide_grid_variant" AS ENUM('cards', 'compact');
  ALTER TABLE "programs_blocks_guide_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_programs_blocks_guide_grid_variant";
  ALTER TABLE "programs_blocks_guide_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_programs_blocks_guide_grid_variant" USING "variant"::"public"."enum_programs_blocks_guide_grid_variant";
  ALTER TABLE "guides_blocks_trip_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "guides_blocks_trip_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_guides_blocks_trip_grid_variant";
  CREATE TYPE "public"."enum_guides_blocks_trip_grid_variant" AS ENUM('cards', 'compact', 'editorial');
  ALTER TABLE "guides_blocks_trip_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_guides_blocks_trip_grid_variant";
  ALTER TABLE "guides_blocks_trip_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_guides_blocks_trip_grid_variant" USING "variant"::"public"."enum_guides_blocks_trip_grid_variant";
  ALTER TABLE "guides_blocks_faq" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "guides_blocks_faq" ALTER COLUMN "variant" SET DEFAULT 'twoColumn'::text;
  DROP TYPE "public"."enum_guides_blocks_faq_variant";
  CREATE TYPE "public"."enum_guides_blocks_faq_variant" AS ENUM('twoColumn', 'singleColumn');
  ALTER TABLE "guides_blocks_faq" ALTER COLUMN "variant" SET DEFAULT 'twoColumn'::"public"."enum_guides_blocks_faq_variant";
  ALTER TABLE "guides_blocks_faq" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_guides_blocks_faq_variant" USING "variant"::"public"."enum_guides_blocks_faq_variant";
  ALTER TABLE "guides_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "guides_blocks_cta" ALTER COLUMN "variant" SET DEFAULT 'dark'::text;
  DROP TYPE "public"."enum_guides_blocks_cta_variant";
  CREATE TYPE "public"."enum_guides_blocks_cta_variant" AS ENUM('dark', 'light', 'red');
  ALTER TABLE "guides_blocks_cta" ALTER COLUMN "variant" SET DEFAULT 'dark'::"public"."enum_guides_blocks_cta_variant";
  ALTER TABLE "guides_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_guides_blocks_cta_variant" USING "variant"::"public"."enum_guides_blocks_cta_variant";
  ALTER TABLE "locations_blocks_trip_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "locations_blocks_trip_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_locations_blocks_trip_grid_variant";
  CREATE TYPE "public"."enum_locations_blocks_trip_grid_variant" AS ENUM('cards', 'compact', 'editorial');
  ALTER TABLE "locations_blocks_trip_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_locations_blocks_trip_grid_variant";
  ALTER TABLE "locations_blocks_trip_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_locations_blocks_trip_grid_variant" USING "variant"::"public"."enum_locations_blocks_trip_grid_variant";
  ALTER TABLE "locations_blocks_faq" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "locations_blocks_faq" ALTER COLUMN "variant" SET DEFAULT 'twoColumn'::text;
  DROP TYPE "public"."enum_locations_blocks_faq_variant";
  CREATE TYPE "public"."enum_locations_blocks_faq_variant" AS ENUM('twoColumn', 'singleColumn');
  ALTER TABLE "locations_blocks_faq" ALTER COLUMN "variant" SET DEFAULT 'twoColumn'::"public"."enum_locations_blocks_faq_variant";
  ALTER TABLE "locations_blocks_faq" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_locations_blocks_faq_variant" USING "variant"::"public"."enum_locations_blocks_faq_variant";
  ALTER TABLE "locations_blocks_guide_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "locations_blocks_guide_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_locations_blocks_guide_grid_variant";
  CREATE TYPE "public"."enum_locations_blocks_guide_grid_variant" AS ENUM('cards', 'compact');
  ALTER TABLE "locations_blocks_guide_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_locations_blocks_guide_grid_variant";
  ALTER TABLE "locations_blocks_guide_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_locations_blocks_guide_grid_variant" USING "variant"::"public"."enum_locations_blocks_guide_grid_variant";
  ALTER TABLE "locations_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "locations_blocks_cta" ALTER COLUMN "variant" SET DEFAULT 'dark'::text;
  DROP TYPE "public"."enum_locations_blocks_cta_variant";
  CREATE TYPE "public"."enum_locations_blocks_cta_variant" AS ENUM('dark', 'light', 'red');
  ALTER TABLE "locations_blocks_cta" ALTER COLUMN "variant" SET DEFAULT 'dark'::"public"."enum_locations_blocks_cta_variant";
  ALTER TABLE "locations_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_locations_blocks_cta_variant" USING "variant"::"public"."enum_locations_blocks_cta_variant";
  ALTER TABLE "events_blocks_faq" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "events_blocks_faq" ALTER COLUMN "variant" SET DEFAULT 'twoColumn'::text;
  DROP TYPE "public"."enum_events_blocks_faq_variant";
  CREATE TYPE "public"."enum_events_blocks_faq_variant" AS ENUM('twoColumn', 'singleColumn');
  ALTER TABLE "events_blocks_faq" ALTER COLUMN "variant" SET DEFAULT 'twoColumn'::"public"."enum_events_blocks_faq_variant";
  ALTER TABLE "events_blocks_faq" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_events_blocks_faq_variant" USING "variant"::"public"."enum_events_blocks_faq_variant";
  ALTER TABLE "posts_blocks_trip_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_trip_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_posts_blocks_trip_grid_variant";
  CREATE TYPE "public"."enum_posts_blocks_trip_grid_variant" AS ENUM('cards', 'compact', 'editorial');
  ALTER TABLE "posts_blocks_trip_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_posts_blocks_trip_grid_variant";
  ALTER TABLE "posts_blocks_trip_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_posts_blocks_trip_grid_variant" USING "variant"::"public"."enum_posts_blocks_trip_grid_variant";
  ALTER TABLE "posts_blocks_program_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_program_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_posts_blocks_program_grid_variant";
  CREATE TYPE "public"."enum_posts_blocks_program_grid_variant" AS ENUM('cards', 'compact');
  ALTER TABLE "posts_blocks_program_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_posts_blocks_program_grid_variant";
  ALTER TABLE "posts_blocks_program_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_posts_blocks_program_grid_variant" USING "variant"::"public"."enum_posts_blocks_program_grid_variant";
  ALTER TABLE "posts_blocks_location_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_location_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_posts_blocks_location_grid_variant";
  CREATE TYPE "public"."enum_posts_blocks_location_grid_variant" AS ENUM('cards', 'compact');
  ALTER TABLE "posts_blocks_location_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_posts_blocks_location_grid_variant";
  ALTER TABLE "posts_blocks_location_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_posts_blocks_location_grid_variant" USING "variant"::"public"."enum_posts_blocks_location_grid_variant";
  ALTER TABLE "posts_blocks_guide_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_guide_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_posts_blocks_guide_grid_variant";
  CREATE TYPE "public"."enum_posts_blocks_guide_grid_variant" AS ENUM('cards', 'compact');
  ALTER TABLE "posts_blocks_guide_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_posts_blocks_guide_grid_variant";
  ALTER TABLE "posts_blocks_guide_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_posts_blocks_guide_grid_variant" USING "variant"::"public"."enum_posts_blocks_guide_grid_variant";
  ALTER TABLE "posts_blocks_faq" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_faq" ALTER COLUMN "variant" SET DEFAULT 'twoColumn'::text;
  DROP TYPE "public"."enum_posts_blocks_faq_variant";
  CREATE TYPE "public"."enum_posts_blocks_faq_variant" AS ENUM('twoColumn', 'singleColumn');
  ALTER TABLE "posts_blocks_faq" ALTER COLUMN "variant" SET DEFAULT 'twoColumn'::"public"."enum_posts_blocks_faq_variant";
  ALTER TABLE "posts_blocks_faq" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_posts_blocks_faq_variant" USING "variant"::"public"."enum_posts_blocks_faq_variant";
  ALTER TABLE "posts_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_cta" ALTER COLUMN "variant" SET DEFAULT 'dark'::text;
  DROP TYPE "public"."enum_posts_blocks_cta_variant";
  CREATE TYPE "public"."enum_posts_blocks_cta_variant" AS ENUM('dark', 'light', 'red');
  ALTER TABLE "posts_blocks_cta" ALTER COLUMN "variant" SET DEFAULT 'dark'::"public"."enum_posts_blocks_cta_variant";
  ALTER TABLE "posts_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_posts_blocks_cta_variant" USING "variant"::"public"."enum_posts_blocks_cta_variant";
  ALTER TABLE "pages_blocks_hero" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_hero" ALTER COLUMN "variant" SET DEFAULT 'overlay'::text;
  DROP TYPE "public"."enum_pages_blocks_hero_variant";
  CREATE TYPE "public"."enum_pages_blocks_hero_variant" AS ENUM('overlay', 'editorial', 'simple');
  ALTER TABLE "pages_blocks_hero" ALTER COLUMN "variant" SET DEFAULT 'overlay'::"public"."enum_pages_blocks_hero_variant";
  ALTER TABLE "pages_blocks_hero" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_pages_blocks_hero_variant" USING "variant"::"public"."enum_pages_blocks_hero_variant";
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "variant" SET DEFAULT 'light'::text;
  DROP TYPE "public"."enum_pages_blocks_stats_variant";
  CREATE TYPE "public"."enum_pages_blocks_stats_variant" AS ENUM('light', 'dark');
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "variant" SET DEFAULT 'light'::"public"."enum_pages_blocks_stats_variant";
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_pages_blocks_stats_variant" USING "variant"::"public"."enum_pages_blocks_stats_variant";
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "variant" SET DEFAULT 'dark'::text;
  DROP TYPE "public"."enum_pages_blocks_cta_variant";
  CREATE TYPE "public"."enum_pages_blocks_cta_variant" AS ENUM('dark', 'light', 'red');
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "variant" SET DEFAULT 'dark'::"public"."enum_pages_blocks_cta_variant";
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_pages_blocks_cta_variant" USING "variant"::"public"."enum_pages_blocks_cta_variant";
  ALTER TABLE "pages_blocks_trip_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_trip_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_pages_blocks_trip_grid_variant";
  CREATE TYPE "public"."enum_pages_blocks_trip_grid_variant" AS ENUM('cards', 'compact', 'editorial');
  ALTER TABLE "pages_blocks_trip_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_pages_blocks_trip_grid_variant";
  ALTER TABLE "pages_blocks_trip_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_pages_blocks_trip_grid_variant" USING "variant"::"public"."enum_pages_blocks_trip_grid_variant";
  ALTER TABLE "pages_blocks_program_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_program_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_pages_blocks_program_grid_variant";
  CREATE TYPE "public"."enum_pages_blocks_program_grid_variant" AS ENUM('cards', 'compact');
  ALTER TABLE "pages_blocks_program_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_pages_blocks_program_grid_variant";
  ALTER TABLE "pages_blocks_program_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_pages_blocks_program_grid_variant" USING "variant"::"public"."enum_pages_blocks_program_grid_variant";
  ALTER TABLE "pages_blocks_location_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_location_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_pages_blocks_location_grid_variant";
  CREATE TYPE "public"."enum_pages_blocks_location_grid_variant" AS ENUM('cards', 'compact');
  ALTER TABLE "pages_blocks_location_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_pages_blocks_location_grid_variant";
  ALTER TABLE "pages_blocks_location_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_pages_blocks_location_grid_variant" USING "variant"::"public"."enum_pages_blocks_location_grid_variant";
  ALTER TABLE "pages_blocks_guide_grid" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_guide_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_pages_blocks_guide_grid_variant";
  CREATE TYPE "public"."enum_pages_blocks_guide_grid_variant" AS ENUM('cards', 'compact');
  ALTER TABLE "pages_blocks_guide_grid" ALTER COLUMN "variant" SET DEFAULT 'cards'::"public"."enum_pages_blocks_guide_grid_variant";
  ALTER TABLE "pages_blocks_guide_grid" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_pages_blocks_guide_grid_variant" USING "variant"::"public"."enum_pages_blocks_guide_grid_variant";
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "variant" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "variant" SET DEFAULT 'twoColumn'::text;
  DROP TYPE "public"."enum_pages_blocks_faq_variant";
  CREATE TYPE "public"."enum_pages_blocks_faq_variant" AS ENUM('twoColumn', 'singleColumn');
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "variant" SET DEFAULT 'twoColumn'::"public"."enum_pages_blocks_faq_variant";
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_pages_blocks_faq_variant" USING "variant"::"public"."enum_pages_blocks_faq_variant";`)
}
