import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    CREATE TYPE "public"."enum_programs_blocks_hero_primary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_programs_blocks_hero_primary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_programs_blocks_cta_primary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_programs_blocks_cta_primary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_programs_blocks_cta_secondary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_programs_blocks_cta_secondary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_guides_blocks_hero_primary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_guides_blocks_hero_primary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_guides_blocks_cta_primary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_guides_blocks_cta_primary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_guides_blocks_cta_secondary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_guides_blocks_cta_secondary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_locations_blocks_hero_primary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_locations_blocks_hero_primary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_locations_blocks_cta_primary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_locations_blocks_cta_primary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_locations_blocks_cta_secondary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_locations_blocks_cta_secondary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_events_blocks_hero_primary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_events_blocks_hero_primary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_events_blocks_cta_primary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_events_blocks_cta_primary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_events_blocks_cta_secondary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_events_blocks_cta_secondary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_posts_blocks_hero_primary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_posts_blocks_hero_primary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_posts_blocks_cta_primary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_posts_blocks_cta_primary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_posts_blocks_cta_secondary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_posts_blocks_cta_secondary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_pages_blocks_hero_primary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_pages_blocks_hero_primary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_pages_blocks_cta_primary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_pages_blocks_cta_primary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');
    CREATE TYPE "public"."enum_pages_blocks_cta_secondary_action_analytics_location" AS ENUM('auto', 'header', 'hero', 'body_cta', 'sidebar', 'footer');
    CREATE TYPE "public"."enum_pages_blocks_cta_secondary_action_analytics_intent" AS ENUM('navigation', 'lead', 'booking', 'contact', 'social', 'download');

    ALTER TABLE "programs_blocks_hero" ADD COLUMN "primary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "programs_blocks_hero" ADD COLUMN "primary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "programs_blocks_hero" ADD COLUMN "primary_action_analytics_action_id" varchar;
    ALTER TABLE "programs_blocks_hero" ADD COLUMN "primary_action_analytics_location" "enum_programs_blocks_hero_primary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "programs_blocks_hero" ADD COLUMN "primary_action_analytics_intent" "enum_programs_blocks_hero_primary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "programs_blocks_hero" ADD COLUMN "primary_action_analytics_custom_label" varchar;
    ALTER TABLE "guides_blocks_hero" ADD COLUMN "primary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "guides_blocks_hero" ADD COLUMN "primary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "guides_blocks_hero" ADD COLUMN "primary_action_analytics_action_id" varchar;
    ALTER TABLE "guides_blocks_hero" ADD COLUMN "primary_action_analytics_location" "enum_guides_blocks_hero_primary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "guides_blocks_hero" ADD COLUMN "primary_action_analytics_intent" "enum_guides_blocks_hero_primary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "guides_blocks_hero" ADD COLUMN "primary_action_analytics_custom_label" varchar;
    ALTER TABLE "locations_blocks_hero" ADD COLUMN "primary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "locations_blocks_hero" ADD COLUMN "primary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "locations_blocks_hero" ADD COLUMN "primary_action_analytics_action_id" varchar;
    ALTER TABLE "locations_blocks_hero" ADD COLUMN "primary_action_analytics_location" "enum_locations_blocks_hero_primary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "locations_blocks_hero" ADD COLUMN "primary_action_analytics_intent" "enum_locations_blocks_hero_primary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "locations_blocks_hero" ADD COLUMN "primary_action_analytics_custom_label" varchar;
    ALTER TABLE "events_blocks_hero" ADD COLUMN "primary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "events_blocks_hero" ADD COLUMN "primary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "events_blocks_hero" ADD COLUMN "primary_action_analytics_action_id" varchar;
    ALTER TABLE "events_blocks_hero" ADD COLUMN "primary_action_analytics_location" "enum_events_blocks_hero_primary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "events_blocks_hero" ADD COLUMN "primary_action_analytics_intent" "enum_events_blocks_hero_primary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "events_blocks_hero" ADD COLUMN "primary_action_analytics_custom_label" varchar;
    ALTER TABLE "posts_blocks_hero" ADD COLUMN "primary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "posts_blocks_hero" ADD COLUMN "primary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "posts_blocks_hero" ADD COLUMN "primary_action_analytics_action_id" varchar;
    ALTER TABLE "posts_blocks_hero" ADD COLUMN "primary_action_analytics_location" "enum_posts_blocks_hero_primary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "posts_blocks_hero" ADD COLUMN "primary_action_analytics_intent" "enum_posts_blocks_hero_primary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "posts_blocks_hero" ADD COLUMN "primary_action_analytics_custom_label" varchar;
    ALTER TABLE "pages_blocks_hero" ADD COLUMN "primary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "pages_blocks_hero" ADD COLUMN "primary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "pages_blocks_hero" ADD COLUMN "primary_action_analytics_action_id" varchar;
    ALTER TABLE "pages_blocks_hero" ADD COLUMN "primary_action_analytics_location" "enum_pages_blocks_hero_primary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "pages_blocks_hero" ADD COLUMN "primary_action_analytics_intent" "enum_pages_blocks_hero_primary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "pages_blocks_hero" ADD COLUMN "primary_action_analytics_custom_label" varchar;

    ALTER TABLE "programs_blocks_cta" ADD COLUMN "primary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "programs_blocks_cta" ADD COLUMN "primary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "programs_blocks_cta" ADD COLUMN "primary_action_analytics_action_id" varchar;
    ALTER TABLE "programs_blocks_cta" ADD COLUMN "primary_action_analytics_location" "enum_programs_blocks_cta_primary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "programs_blocks_cta" ADD COLUMN "primary_action_analytics_intent" "enum_programs_blocks_cta_primary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "programs_blocks_cta" ADD COLUMN "primary_action_analytics_custom_label" varchar;
    ALTER TABLE "programs_blocks_cta" ADD COLUMN "secondary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "programs_blocks_cta" ADD COLUMN "secondary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "programs_blocks_cta" ADD COLUMN "secondary_action_analytics_action_id" varchar;
    ALTER TABLE "programs_blocks_cta" ADD COLUMN "secondary_action_analytics_location" "enum_programs_blocks_cta_secondary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "programs_blocks_cta" ADD COLUMN "secondary_action_analytics_intent" "enum_programs_blocks_cta_secondary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "programs_blocks_cta" ADD COLUMN "secondary_action_analytics_custom_label" varchar;
    ALTER TABLE "guides_blocks_cta" ADD COLUMN "primary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "guides_blocks_cta" ADD COLUMN "primary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "guides_blocks_cta" ADD COLUMN "primary_action_analytics_action_id" varchar;
    ALTER TABLE "guides_blocks_cta" ADD COLUMN "primary_action_analytics_location" "enum_guides_blocks_cta_primary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "guides_blocks_cta" ADD COLUMN "primary_action_analytics_intent" "enum_guides_blocks_cta_primary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "guides_blocks_cta" ADD COLUMN "primary_action_analytics_custom_label" varchar;
    ALTER TABLE "guides_blocks_cta" ADD COLUMN "secondary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "guides_blocks_cta" ADD COLUMN "secondary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "guides_blocks_cta" ADD COLUMN "secondary_action_analytics_action_id" varchar;
    ALTER TABLE "guides_blocks_cta" ADD COLUMN "secondary_action_analytics_location" "enum_guides_blocks_cta_secondary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "guides_blocks_cta" ADD COLUMN "secondary_action_analytics_intent" "enum_guides_blocks_cta_secondary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "guides_blocks_cta" ADD COLUMN "secondary_action_analytics_custom_label" varchar;
    ALTER TABLE "locations_blocks_cta" ADD COLUMN "primary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "locations_blocks_cta" ADD COLUMN "primary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "locations_blocks_cta" ADD COLUMN "primary_action_analytics_action_id" varchar;
    ALTER TABLE "locations_blocks_cta" ADD COLUMN "primary_action_analytics_location" "enum_locations_blocks_cta_primary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "locations_blocks_cta" ADD COLUMN "primary_action_analytics_intent" "enum_locations_blocks_cta_primary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "locations_blocks_cta" ADD COLUMN "primary_action_analytics_custom_label" varchar;
    ALTER TABLE "locations_blocks_cta" ADD COLUMN "secondary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "locations_blocks_cta" ADD COLUMN "secondary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "locations_blocks_cta" ADD COLUMN "secondary_action_analytics_action_id" varchar;
    ALTER TABLE "locations_blocks_cta" ADD COLUMN "secondary_action_analytics_location" "enum_locations_blocks_cta_secondary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "locations_blocks_cta" ADD COLUMN "secondary_action_analytics_intent" "enum_locations_blocks_cta_secondary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "locations_blocks_cta" ADD COLUMN "secondary_action_analytics_custom_label" varchar;
    ALTER TABLE "events_blocks_cta" ADD COLUMN "primary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "events_blocks_cta" ADD COLUMN "primary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "events_blocks_cta" ADD COLUMN "primary_action_analytics_action_id" varchar;
    ALTER TABLE "events_blocks_cta" ADD COLUMN "primary_action_analytics_location" "enum_events_blocks_cta_primary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "events_blocks_cta" ADD COLUMN "primary_action_analytics_intent" "enum_events_blocks_cta_primary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "events_blocks_cta" ADD COLUMN "primary_action_analytics_custom_label" varchar;
    ALTER TABLE "events_blocks_cta" ADD COLUMN "secondary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "events_blocks_cta" ADD COLUMN "secondary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "events_blocks_cta" ADD COLUMN "secondary_action_analytics_action_id" varchar;
    ALTER TABLE "events_blocks_cta" ADD COLUMN "secondary_action_analytics_location" "enum_events_blocks_cta_secondary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "events_blocks_cta" ADD COLUMN "secondary_action_analytics_intent" "enum_events_blocks_cta_secondary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "events_blocks_cta" ADD COLUMN "secondary_action_analytics_custom_label" varchar;
    ALTER TABLE "posts_blocks_cta" ADD COLUMN "primary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "posts_blocks_cta" ADD COLUMN "primary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "posts_blocks_cta" ADD COLUMN "primary_action_analytics_action_id" varchar;
    ALTER TABLE "posts_blocks_cta" ADD COLUMN "primary_action_analytics_location" "enum_posts_blocks_cta_primary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "posts_blocks_cta" ADD COLUMN "primary_action_analytics_intent" "enum_posts_blocks_cta_primary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "posts_blocks_cta" ADD COLUMN "primary_action_analytics_custom_label" varchar;
    ALTER TABLE "posts_blocks_cta" ADD COLUMN "secondary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "posts_blocks_cta" ADD COLUMN "secondary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "posts_blocks_cta" ADD COLUMN "secondary_action_analytics_action_id" varchar;
    ALTER TABLE "posts_blocks_cta" ADD COLUMN "secondary_action_analytics_location" "enum_posts_blocks_cta_secondary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "posts_blocks_cta" ADD COLUMN "secondary_action_analytics_intent" "enum_posts_blocks_cta_secondary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "posts_blocks_cta" ADD COLUMN "secondary_action_analytics_custom_label" varchar;
    ALTER TABLE "pages_blocks_cta" ADD COLUMN "primary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "pages_blocks_cta" ADD COLUMN "primary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "pages_blocks_cta" ADD COLUMN "primary_action_analytics_action_id" varchar;
    ALTER TABLE "pages_blocks_cta" ADD COLUMN "primary_action_analytics_location" "enum_pages_blocks_cta_primary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "pages_blocks_cta" ADD COLUMN "primary_action_analytics_intent" "enum_pages_blocks_cta_primary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "pages_blocks_cta" ADD COLUMN "primary_action_analytics_custom_label" varchar;
    ALTER TABLE "pages_blocks_cta" ADD COLUMN "secondary_action_analytics_enabled" boolean DEFAULT true;
    ALTER TABLE "pages_blocks_cta" ADD COLUMN "secondary_action_analytics_event_name" varchar DEFAULT 'cta_click';
    ALTER TABLE "pages_blocks_cta" ADD COLUMN "secondary_action_analytics_action_id" varchar;
    ALTER TABLE "pages_blocks_cta" ADD COLUMN "secondary_action_analytics_location" "enum_pages_blocks_cta_secondary_action_analytics_location" DEFAULT 'auto';
    ALTER TABLE "pages_blocks_cta" ADD COLUMN "secondary_action_analytics_intent" "enum_pages_blocks_cta_secondary_action_analytics_intent" DEFAULT 'navigation';
    ALTER TABLE "pages_blocks_cta" ADD COLUMN "secondary_action_analytics_custom_label" varchar;
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
    ALTER TABLE "programs_blocks_hero" DROP COLUMN "primary_action_analytics_enabled";
    ALTER TABLE "programs_blocks_hero" DROP COLUMN "primary_action_analytics_event_name";
    ALTER TABLE "programs_blocks_hero" DROP COLUMN "primary_action_analytics_action_id";
    ALTER TABLE "programs_blocks_hero" DROP COLUMN "primary_action_analytics_location";
    ALTER TABLE "programs_blocks_hero" DROP COLUMN "primary_action_analytics_intent";
    ALTER TABLE "programs_blocks_hero" DROP COLUMN "primary_action_analytics_custom_label";
    ALTER TABLE "guides_blocks_hero" DROP COLUMN "primary_action_analytics_enabled";
    ALTER TABLE "guides_blocks_hero" DROP COLUMN "primary_action_analytics_event_name";
    ALTER TABLE "guides_blocks_hero" DROP COLUMN "primary_action_analytics_action_id";
    ALTER TABLE "guides_blocks_hero" DROP COLUMN "primary_action_analytics_location";
    ALTER TABLE "guides_blocks_hero" DROP COLUMN "primary_action_analytics_intent";
    ALTER TABLE "guides_blocks_hero" DROP COLUMN "primary_action_analytics_custom_label";
    ALTER TABLE "locations_blocks_hero" DROP COLUMN "primary_action_analytics_enabled";
    ALTER TABLE "locations_blocks_hero" DROP COLUMN "primary_action_analytics_event_name";
    ALTER TABLE "locations_blocks_hero" DROP COLUMN "primary_action_analytics_action_id";
    ALTER TABLE "locations_blocks_hero" DROP COLUMN "primary_action_analytics_location";
    ALTER TABLE "locations_blocks_hero" DROP COLUMN "primary_action_analytics_intent";
    ALTER TABLE "locations_blocks_hero" DROP COLUMN "primary_action_analytics_custom_label";
    ALTER TABLE "events_blocks_hero" DROP COLUMN "primary_action_analytics_enabled";
    ALTER TABLE "events_blocks_hero" DROP COLUMN "primary_action_analytics_event_name";
    ALTER TABLE "events_blocks_hero" DROP COLUMN "primary_action_analytics_action_id";
    ALTER TABLE "events_blocks_hero" DROP COLUMN "primary_action_analytics_location";
    ALTER TABLE "events_blocks_hero" DROP COLUMN "primary_action_analytics_intent";
    ALTER TABLE "events_blocks_hero" DROP COLUMN "primary_action_analytics_custom_label";
    ALTER TABLE "posts_blocks_hero" DROP COLUMN "primary_action_analytics_enabled";
    ALTER TABLE "posts_blocks_hero" DROP COLUMN "primary_action_analytics_event_name";
    ALTER TABLE "posts_blocks_hero" DROP COLUMN "primary_action_analytics_action_id";
    ALTER TABLE "posts_blocks_hero" DROP COLUMN "primary_action_analytics_location";
    ALTER TABLE "posts_blocks_hero" DROP COLUMN "primary_action_analytics_intent";
    ALTER TABLE "posts_blocks_hero" DROP COLUMN "primary_action_analytics_custom_label";
    ALTER TABLE "pages_blocks_hero" DROP COLUMN "primary_action_analytics_enabled";
    ALTER TABLE "pages_blocks_hero" DROP COLUMN "primary_action_analytics_event_name";
    ALTER TABLE "pages_blocks_hero" DROP COLUMN "primary_action_analytics_action_id";
    ALTER TABLE "pages_blocks_hero" DROP COLUMN "primary_action_analytics_location";
    ALTER TABLE "pages_blocks_hero" DROP COLUMN "primary_action_analytics_intent";
    ALTER TABLE "pages_blocks_hero" DROP COLUMN "primary_action_analytics_custom_label";

    ALTER TABLE "programs_blocks_cta" DROP COLUMN "primary_action_analytics_enabled";
    ALTER TABLE "programs_blocks_cta" DROP COLUMN "primary_action_analytics_event_name";
    ALTER TABLE "programs_blocks_cta" DROP COLUMN "primary_action_analytics_action_id";
    ALTER TABLE "programs_blocks_cta" DROP COLUMN "primary_action_analytics_location";
    ALTER TABLE "programs_blocks_cta" DROP COLUMN "primary_action_analytics_intent";
    ALTER TABLE "programs_blocks_cta" DROP COLUMN "primary_action_analytics_custom_label";
    ALTER TABLE "programs_blocks_cta" DROP COLUMN "secondary_action_analytics_enabled";
    ALTER TABLE "programs_blocks_cta" DROP COLUMN "secondary_action_analytics_event_name";
    ALTER TABLE "programs_blocks_cta" DROP COLUMN "secondary_action_analytics_action_id";
    ALTER TABLE "programs_blocks_cta" DROP COLUMN "secondary_action_analytics_location";
    ALTER TABLE "programs_blocks_cta" DROP COLUMN "secondary_action_analytics_intent";
    ALTER TABLE "programs_blocks_cta" DROP COLUMN "secondary_action_analytics_custom_label";
    ALTER TABLE "guides_blocks_cta" DROP COLUMN "primary_action_analytics_enabled";
    ALTER TABLE "guides_blocks_cta" DROP COLUMN "primary_action_analytics_event_name";
    ALTER TABLE "guides_blocks_cta" DROP COLUMN "primary_action_analytics_action_id";
    ALTER TABLE "guides_blocks_cta" DROP COLUMN "primary_action_analytics_location";
    ALTER TABLE "guides_blocks_cta" DROP COLUMN "primary_action_analytics_intent";
    ALTER TABLE "guides_blocks_cta" DROP COLUMN "primary_action_analytics_custom_label";
    ALTER TABLE "guides_blocks_cta" DROP COLUMN "secondary_action_analytics_enabled";
    ALTER TABLE "guides_blocks_cta" DROP COLUMN "secondary_action_analytics_event_name";
    ALTER TABLE "guides_blocks_cta" DROP COLUMN "secondary_action_analytics_action_id";
    ALTER TABLE "guides_blocks_cta" DROP COLUMN "secondary_action_analytics_location";
    ALTER TABLE "guides_blocks_cta" DROP COLUMN "secondary_action_analytics_intent";
    ALTER TABLE "guides_blocks_cta" DROP COLUMN "secondary_action_analytics_custom_label";
    ALTER TABLE "locations_blocks_cta" DROP COLUMN "primary_action_analytics_enabled";
    ALTER TABLE "locations_blocks_cta" DROP COLUMN "primary_action_analytics_event_name";
    ALTER TABLE "locations_blocks_cta" DROP COLUMN "primary_action_analytics_action_id";
    ALTER TABLE "locations_blocks_cta" DROP COLUMN "primary_action_analytics_location";
    ALTER TABLE "locations_blocks_cta" DROP COLUMN "primary_action_analytics_intent";
    ALTER TABLE "locations_blocks_cta" DROP COLUMN "primary_action_analytics_custom_label";
    ALTER TABLE "locations_blocks_cta" DROP COLUMN "secondary_action_analytics_enabled";
    ALTER TABLE "locations_blocks_cta" DROP COLUMN "secondary_action_analytics_event_name";
    ALTER TABLE "locations_blocks_cta" DROP COLUMN "secondary_action_analytics_action_id";
    ALTER TABLE "locations_blocks_cta" DROP COLUMN "secondary_action_analytics_location";
    ALTER TABLE "locations_blocks_cta" DROP COLUMN "secondary_action_analytics_intent";
    ALTER TABLE "locations_blocks_cta" DROP COLUMN "secondary_action_analytics_custom_label";
    ALTER TABLE "events_blocks_cta" DROP COLUMN "primary_action_analytics_enabled";
    ALTER TABLE "events_blocks_cta" DROP COLUMN "primary_action_analytics_event_name";
    ALTER TABLE "events_blocks_cta" DROP COLUMN "primary_action_analytics_action_id";
    ALTER TABLE "events_blocks_cta" DROP COLUMN "primary_action_analytics_location";
    ALTER TABLE "events_blocks_cta" DROP COLUMN "primary_action_analytics_intent";
    ALTER TABLE "events_blocks_cta" DROP COLUMN "primary_action_analytics_custom_label";
    ALTER TABLE "events_blocks_cta" DROP COLUMN "secondary_action_analytics_enabled";
    ALTER TABLE "events_blocks_cta" DROP COLUMN "secondary_action_analytics_event_name";
    ALTER TABLE "events_blocks_cta" DROP COLUMN "secondary_action_analytics_action_id";
    ALTER TABLE "events_blocks_cta" DROP COLUMN "secondary_action_analytics_location";
    ALTER TABLE "events_blocks_cta" DROP COLUMN "secondary_action_analytics_intent";
    ALTER TABLE "events_blocks_cta" DROP COLUMN "secondary_action_analytics_custom_label";
    ALTER TABLE "posts_blocks_cta" DROP COLUMN "primary_action_analytics_enabled";
    ALTER TABLE "posts_blocks_cta" DROP COLUMN "primary_action_analytics_event_name";
    ALTER TABLE "posts_blocks_cta" DROP COLUMN "primary_action_analytics_action_id";
    ALTER TABLE "posts_blocks_cta" DROP COLUMN "primary_action_analytics_location";
    ALTER TABLE "posts_blocks_cta" DROP COLUMN "primary_action_analytics_intent";
    ALTER TABLE "posts_blocks_cta" DROP COLUMN "primary_action_analytics_custom_label";
    ALTER TABLE "posts_blocks_cta" DROP COLUMN "secondary_action_analytics_enabled";
    ALTER TABLE "posts_blocks_cta" DROP COLUMN "secondary_action_analytics_event_name";
    ALTER TABLE "posts_blocks_cta" DROP COLUMN "secondary_action_analytics_action_id";
    ALTER TABLE "posts_blocks_cta" DROP COLUMN "secondary_action_analytics_location";
    ALTER TABLE "posts_blocks_cta" DROP COLUMN "secondary_action_analytics_intent";
    ALTER TABLE "posts_blocks_cta" DROP COLUMN "secondary_action_analytics_custom_label";
    ALTER TABLE "pages_blocks_cta" DROP COLUMN "primary_action_analytics_enabled";
    ALTER TABLE "pages_blocks_cta" DROP COLUMN "primary_action_analytics_event_name";
    ALTER TABLE "pages_blocks_cta" DROP COLUMN "primary_action_analytics_action_id";
    ALTER TABLE "pages_blocks_cta" DROP COLUMN "primary_action_analytics_location";
    ALTER TABLE "pages_blocks_cta" DROP COLUMN "primary_action_analytics_intent";
    ALTER TABLE "pages_blocks_cta" DROP COLUMN "primary_action_analytics_custom_label";
    ALTER TABLE "pages_blocks_cta" DROP COLUMN "secondary_action_analytics_enabled";
    ALTER TABLE "pages_blocks_cta" DROP COLUMN "secondary_action_analytics_event_name";
    ALTER TABLE "pages_blocks_cta" DROP COLUMN "secondary_action_analytics_action_id";
    ALTER TABLE "pages_blocks_cta" DROP COLUMN "secondary_action_analytics_location";
    ALTER TABLE "pages_blocks_cta" DROP COLUMN "secondary_action_analytics_intent";
    ALTER TABLE "pages_blocks_cta" DROP COLUMN "secondary_action_analytics_custom_label";

    DROP TYPE "public"."enum_programs_blocks_hero_primary_action_analytics_location";
    DROP TYPE "public"."enum_programs_blocks_hero_primary_action_analytics_intent";
    DROP TYPE "public"."enum_programs_blocks_cta_primary_action_analytics_location";
    DROP TYPE "public"."enum_programs_blocks_cta_primary_action_analytics_intent";
    DROP TYPE "public"."enum_programs_blocks_cta_secondary_action_analytics_location";
    DROP TYPE "public"."enum_programs_blocks_cta_secondary_action_analytics_intent";
    DROP TYPE "public"."enum_guides_blocks_hero_primary_action_analytics_location";
    DROP TYPE "public"."enum_guides_blocks_hero_primary_action_analytics_intent";
    DROP TYPE "public"."enum_guides_blocks_cta_primary_action_analytics_location";
    DROP TYPE "public"."enum_guides_blocks_cta_primary_action_analytics_intent";
    DROP TYPE "public"."enum_guides_blocks_cta_secondary_action_analytics_location";
    DROP TYPE "public"."enum_guides_blocks_cta_secondary_action_analytics_intent";
    DROP TYPE "public"."enum_locations_blocks_hero_primary_action_analytics_location";
    DROP TYPE "public"."enum_locations_blocks_hero_primary_action_analytics_intent";
    DROP TYPE "public"."enum_locations_blocks_cta_primary_action_analytics_location";
    DROP TYPE "public"."enum_locations_blocks_cta_primary_action_analytics_intent";
    DROP TYPE "public"."enum_locations_blocks_cta_secondary_action_analytics_location";
    DROP TYPE "public"."enum_locations_blocks_cta_secondary_action_analytics_intent";
    DROP TYPE "public"."enum_events_blocks_hero_primary_action_analytics_location";
    DROP TYPE "public"."enum_events_blocks_hero_primary_action_analytics_intent";
    DROP TYPE "public"."enum_events_blocks_cta_primary_action_analytics_location";
    DROP TYPE "public"."enum_events_blocks_cta_primary_action_analytics_intent";
    DROP TYPE "public"."enum_events_blocks_cta_secondary_action_analytics_location";
    DROP TYPE "public"."enum_events_blocks_cta_secondary_action_analytics_intent";
    DROP TYPE "public"."enum_posts_blocks_hero_primary_action_analytics_location";
    DROP TYPE "public"."enum_posts_blocks_hero_primary_action_analytics_intent";
    DROP TYPE "public"."enum_posts_blocks_cta_primary_action_analytics_location";
    DROP TYPE "public"."enum_posts_blocks_cta_primary_action_analytics_intent";
    DROP TYPE "public"."enum_posts_blocks_cta_secondary_action_analytics_location";
    DROP TYPE "public"."enum_posts_blocks_cta_secondary_action_analytics_intent";
    DROP TYPE "public"."enum_pages_blocks_hero_primary_action_analytics_location";
    DROP TYPE "public"."enum_pages_blocks_hero_primary_action_analytics_intent";
    DROP TYPE "public"."enum_pages_blocks_cta_primary_action_analytics_location";
    DROP TYPE "public"."enum_pages_blocks_cta_primary_action_analytics_intent";
    DROP TYPE "public"."enum_pages_blocks_cta_secondary_action_analytics_location";
    DROP TYPE "public"."enum_pages_blocks_cta_secondary_action_analytics_intent";
  `)
}
