/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    difficulties: Difficulty;
    types: Type;
    categories: Category;
    guides: Guide;
    locations: Location;
    airports: Airport;
    partners: Partner;
    events: Event;
    'event-dates': EventDate;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    difficulties: DifficultiesSelect<false> | DifficultiesSelect<true>;
    types: TypesSelect<false> | TypesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    airports: AirportsSelect<false> | AirportsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-dates': EventDatesSelect<false> | EventDatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'customer' | 'admin';
  addresses?:
    | {
        street?: string | null;
        city?: string | null;
        postalCode?: string | null;
        country?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "difficulties".
 */
export interface Difficulty {
  id: number;
  name: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "types".
 */
export interface Type {
  id: number;
  name: string;
  slug: string;
  shortDescription?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mainPicture?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  vimeoId?: string | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  audienceCards?:
    | {
        heading: string;
        body: string;
        highlighted?: boolean | null;
        id?: string | null;
      }[]
    | null;
  soloNote?: string | null;
  redirectCallout?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  curriculumPillars?:
    | {
        icon?: string | null;
        title: string;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  programFlow?: {
    framingParagraph?: string | null;
    mixAndMatchBlocks?:
      | {
          title: string;
          tagline?: string | null;
          bullets?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    tailoredToYou?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    focusTracks?:
      | {
          title: string;
          colorTag?: ('red' | 'blue' | 'green') | null;
          bullets?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  weekVariants?:
    | {
        title: string;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  weekRecommendation?: string | null;
  accommodation?: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    included?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    foodBeverages?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    notIncluded?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  transport?: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    airports?: (number | Airport)[] | null;
  };
  coachFramingParagraph?: string | null;
  coaches?: (number | Guide)[] | null;
  results?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  active?: boolean | null;
  state: 'draft' | 'published';
  seo?: {
    title?: string | null;
    keywords?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "airports".
 */
export interface Airport {
  id: number;
  name: string;
  iata: string;
  country?: string | null;
  continent?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  size?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  name: string;
  slug: string;
  photo?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  email?: string | null;
  phone?: string | null;
  vimeoId?: string | null;
  featured?: boolean | null;
  active?: boolean | null;
  seo?: {
    title?: string | null;
    keywords?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  text?: string | null;
  position?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  address?: string | null;
  city?: string | null;
  country?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  active?: boolean | null;
  seo?: {
    title?: string | null;
    keywords?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  slug: string;
  link?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (number | null) | Media;
  featured?: boolean | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  shortDescription?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  additionalInfo?:
    | {
        heading: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  mainPicture?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  vimeoId?: string | null;
  categories?: (number | Category)[] | null;
  difficulties?: (number | Difficulty)[] | null;
  types?: (number | Type)[] | null;
  locations?: (number | Location)[] | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  audienceCards?:
    | {
        heading: string;
        body: string;
        highlighted?: boolean | null;
        id?: string | null;
      }[]
    | null;
  prerequisites?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  equipmentIntro?: string | null;
  essentialEquipment?:
    | {
        icon?: string | null;
        name: string;
        note?: string | null;
        mandatory?: boolean | null;
        id?: string | null;
      }[]
    | null;
  whatYouLearn?: {
    intro?: string | null;
    box1Heading?: string | null;
    box1Bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    box2Heading?: string | null;
    box2Bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  itinerary?: {
    intro?: string | null;
    days?:
      | {
          dayBadge?: string | null;
          destinationIcon?: string | null;
          destinationName: string;
          metaLine?: string | null;
          eyebrow?: string | null;
          heading?: string | null;
          description?: string | null;
          highlightTags?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          schedule?:
            | {
                time: string;
                activity: string;
                id?: string | null;
              }[]
            | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  accommodation?: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    included?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    notIncluded?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    cuisineHighlights?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  transport?: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    airports?: (number | Airport)[] | null;
  };
  coachFramingParagraph?: string | null;
  coaches?: (number | Guide)[] | null;
  coachTeamBullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  partner?: (number | null) | Partner;
  partnerEyebrow?: string | null;
  partnerHeadline?: string | null;
  partnerDescription?: string | null;
  partnerBenefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  state: 'draft' | 'published';
  seo?: {
    title?: string | null;
    keywords?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-dates".
 */
export interface EventDate {
  id: number;
  event: number | Event;
  dateFrom: string;
  dateTo: string;
  locations?: (number | Location)[] | null;
  guides?: (number | Guide)[] | null;
  airportFrom?: (number | null) | Airport;
  airportTo?: (number | null) | Airport;
  price: number;
  vat: number;
  currency: 'EUR' | 'CZK';
  capacity: number;
  minParticipants?: number | null;
  extraContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'difficulties';
        value: number | Difficulty;
      } | null)
    | ({
        relationTo: 'types';
        value: number | Type;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'airports';
        value: number | Airport;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-dates';
        value: number | EventDate;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  addresses?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "difficulties_select".
 */
export interface DifficultiesSelect<T extends boolean = true> {
  name?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "types_select".
 */
export interface TypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  content?: T;
  mainPicture?: T;
  gallery?: T;
  vimeoId?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  audienceCards?:
    | T
    | {
        heading?: T;
        body?: T;
        highlighted?: T;
        id?: T;
      };
  soloNote?: T;
  redirectCallout?: T;
  curriculumPillars?:
    | T
    | {
        icon?: T;
        title?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  programFlow?:
    | T
    | {
        framingParagraph?: T;
        mixAndMatchBlocks?:
          | T
          | {
              title?: T;
              tagline?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
        tailoredToYou?:
          | T
          | {
              text?: T;
              id?: T;
            };
        focusTracks?:
          | T
          | {
              title?: T;
              colorTag?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  weekVariants?:
    | T
    | {
        title?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  weekRecommendation?: T;
  accommodation?:
    | T
    | {
        description?: T;
        included?:
          | T
          | {
              text?: T;
              id?: T;
            };
        foodBeverages?:
          | T
          | {
              text?: T;
              id?: T;
            };
        notIncluded?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  transport?:
    | T
    | {
        description?: T;
        airports?: T;
      };
  coachFramingParagraph?: T;
  coaches?: T;
  results?:
    | T
    | {
        text?: T;
        id?: T;
      };
  featured?: T;
  active?: T;
  state?: T;
  seo?:
    | T
    | {
        title?: T;
        keywords?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  text?: T;
  position?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  content?: T;
  email?: T;
  phone?: T;
  vimeoId?: T;
  featured?: T;
  active?: T;
  seo?:
    | T
    | {
        title?: T;
        keywords?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  content?: T;
  address?: T;
  city?: T;
  country?: T;
  coordinates?: T;
  active?: T;
  seo?:
    | T
    | {
        title?: T;
        keywords?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "airports_select".
 */
export interface AirportsSelect<T extends boolean = true> {
  name?: T;
  iata?: T;
  country?: T;
  continent?: T;
  coordinates?: T;
  size?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  link?: T;
  description?: T;
  logo?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  content?: T;
  additionalInfo?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  mainPicture?: T;
  gallery?: T;
  vimeoId?: T;
  categories?: T;
  difficulties?: T;
  types?: T;
  locations?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  audienceCards?:
    | T
    | {
        heading?: T;
        body?: T;
        highlighted?: T;
        id?: T;
      };
  prerequisites?:
    | T
    | {
        text?: T;
        id?: T;
      };
  equipmentIntro?: T;
  essentialEquipment?:
    | T
    | {
        icon?: T;
        name?: T;
        note?: T;
        mandatory?: T;
        id?: T;
      };
  whatYouLearn?:
    | T
    | {
        intro?: T;
        box1Heading?: T;
        box1Bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        box2Heading?: T;
        box2Bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  itinerary?:
    | T
    | {
        intro?: T;
        days?:
          | T
          | {
              dayBadge?: T;
              destinationIcon?: T;
              destinationName?: T;
              metaLine?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              highlightTags?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              schedule?:
                | T
                | {
                    time?: T;
                    activity?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
            };
      };
  accommodation?:
    | T
    | {
        description?: T;
        included?:
          | T
          | {
              text?: T;
              id?: T;
            };
        notIncluded?:
          | T
          | {
              text?: T;
              id?: T;
            };
        cuisineHighlights?: T;
      };
  transport?:
    | T
    | {
        description?: T;
        airports?: T;
      };
  coachFramingParagraph?: T;
  coaches?: T;
  coachTeamBullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  partner?: T;
  partnerEyebrow?: T;
  partnerHeadline?: T;
  partnerDescription?: T;
  partnerBenefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  featured?: T;
  state?: T;
  seo?:
    | T
    | {
        title?: T;
        keywords?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-dates_select".
 */
export interface EventDatesSelect<T extends boolean = true> {
  event?: T;
  dateFrom?: T;
  dateTo?: T;
  locations?: T;
  guides?: T;
  airportFrom?: T;
  airportTo?: T;
  price?: T;
  vat?: T;
  currency?: T;
  capacity?: T;
  minParticipants?: T;
  extraContent?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}