/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    difficulties: Difficulty;
    programs: Program;
    categories: Category;
    guides: Guide;
    locations: Location;
    airports: Airport;
    partners: Partner;
    events: Event;
    'event-dates': EventDate;
    faqs: Faq;
    reviews: Review;
    orders: Order;
    'discount-codes': DiscountCode;
    referrals: Referral;
    'post-categories': PostCategory;
    posts: Post;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    difficulties: DifficultiesSelect<false> | DifficultiesSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    airports: AirportsSelect<false> | AirportsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-dates': EventDatesSelect<false> | EventDatesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'discount-codes': DiscountCodesSelect<false> | DiscountCodesSelect<true>;
    referrals: ReferralsSelect<false> | ReferralsSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  phone: string;
  role: 'customer' | 'admin';
  addresses?:
    | {
        label?: string | null;
        isDefault?: boolean | null;
        firstName: string;
        lastName: string;
        street: string;
        city: string;
        postalCode: string;
        country: string;
        company?: {
          companyName?: string | null;
          ico?: string | null;
          dic?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  pendingEmail?: string | null;
  pendingEmailToken?: string | null;
  pendingEmailExpiresAt?: string | null;
  lastVerifyEmailSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "difficulties".
 */
export interface Difficulty {
  id: number;
  name: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  name: string;
  slug: string;
  shortDescription?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mainPicture?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  vimeoId?: string | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  audienceCards?:
    | {
        heading: string;
        body: string;
        highlighted?: boolean | null;
        id?: string | null;
      }[]
    | null;
  soloNote?: string | null;
  redirectCallout?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  curriculumPillars?:
    | {
        icon?: string | null;
        title: string;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  flow?: {
    framingParagraph?: string | null;
    mixAndMatchBlocks?:
      | {
          title: string;
          tagline?: string | null;
          bullets?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    tailoredToYou?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    focusTracks?:
      | {
          title: string;
          colorTag?: ('red' | 'blue' | 'green') | null;
          bullets?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  weekVariants?:
    | {
        title: string;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  weekRecommendation?: string | null;
  accommodation?: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    included?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    foodBeverages?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    notIncluded?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  transport?: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    airports?: (number | Airport)[] | null;
  };
  coachFramingParagraph?: string | null;
  coaches?: (number | Guide)[] | null;
  results?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  active?: boolean | null;
  state: 'draft' | 'published';
  seo?: {
    title?: string | null;
    keywords?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "airports".
 */
export interface Airport {
  id: number;
  name: string;
  iata: string;
  country?: string | null;
  continent?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  size?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  name: string;
  slug: string;
  /**
   * e.g. Head coach, Pro climber, Physiotherapist
   */
  role?: string | null;
  /**
   * Punchy one-liner shown on team cards and the profile hero.
   */
  tagline?: string | null;
  /**
   * Short badges, ~3 max. e.g. "Sport 9b", "Basque", "UIAGM".
   */
  tags?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  section: 'team' | 'friends';
  photo?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  email?: string | null;
  phone?: string | null;
  vimeoId?: string | null;
  /**
   * Hero subtitle paragraph under the name. Falls back to tagline when empty.
   */
  heroSub?: string | null;
  /**
   * Photo credit, e.g. "Jany · Pince Sans Rire 7b+".
   */
  heroCaption?: string | null;
  /**
   * Stats bar under the hero, ~4 items (value "25+", label "Years Climbing & Coaching").
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * About section. Bio paragraphs come from the content richtext field.
   */
  about?: {
    /**
     * One display line per row; wrap a line in *asterisks* to render it red.
     */
    headline?: string | null;
    /**
     * Facts card rows. Never put email/phone here — public pages must not leak contacts.
     */
    facts?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    quote?: string | null;
    /**
     * e.g. "— Jany, on how he coaches"
     */
    quoteAttribution?: string | null;
  };
  /**
   * "What X coaches" numbered pillars.
   */
  coaching?: {
    intro?: string | null;
    pillars?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * "On the rock" route list.
   */
  achievements?: {
    intro?: string | null;
    items?:
      | {
          route: string;
          location?: string | null;
          grade?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Single client testimonial (always rendered with five stars).
   */
  testimonial?: {
    quote?: string | null;
    name?: string | null;
    /**
     * e.g. "Rockbusters Road Trip Client"
     */
    tripLine?: string | null;
  };
  featured?: boolean | null;
  /**
   * Mark the founder card on the homepage.
   */
  isFounder?: boolean | null;
  active?: boolean | null;
  seo?: {
    title?: string | null;
    keywords?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  text?: string | null;
  position?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  address?: string | null;
  city?: string | null;
  country?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  mainPicture?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  featured?: boolean | null;
  active?: boolean | null;
  seo?: {
    title?: string | null;
    keywords?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  slug: string;
  link?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (number | null) | Media;
  featured?: boolean | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  shortDescription?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  additionalInfo?:
    | {
        heading: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  mainPicture?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  vimeoId?: string | null;
  categories?: (number | Category)[] | null;
  difficulties?: (number | Difficulty)[] | null;
  programs?: (number | Program)[] | null;
  locations?: (number | Location)[] | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  audienceCards?:
    | {
        heading: string;
        body: string;
        highlighted?: boolean | null;
        id?: string | null;
      }[]
    | null;
  prerequisites?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  equipmentIntro?: string | null;
  essentialEquipment?:
    | {
        icon?: string | null;
        name: string;
        note?: string | null;
        mandatory?: boolean | null;
        id?: string | null;
      }[]
    | null;
  whatYouLearn?: {
    intro?: string | null;
    box1Heading?: string | null;
    box1Bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    box2Heading?: string | null;
    box2Bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  itinerary?: {
    intro?: string | null;
    days?:
      | {
          dayBadge?: string | null;
          destinationIcon?: string | null;
          destinationName: string;
          metaLine?: string | null;
          eyebrow?: string | null;
          heading?: string | null;
          description?: string | null;
          highlightTags?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          schedule?:
            | {
                time: string;
                activity: string;
                id?: string | null;
              }[]
            | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  accommodation?: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    included?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    notIncluded?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    cuisineHighlights?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  transport?: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    airports?: (number | Airport)[] | null;
  };
  coachFramingParagraph?: string | null;
  coaches?: (number | Guide)[] | null;
  coachTeamBullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  partner?: (number | null) | Partner;
  partnerEyebrow?: string | null;
  partnerHeadline?: string | null;
  partnerDescription?: string | null;
  partnerBenefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  demoEnabled?: boolean | null;
  demoHeading?: string | null;
  demoBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  demoCta?: {
    label?: string | null;
    url?: string | null;
  };
  featured?: boolean | null;
  state: 'draft' | 'published';
  seo?: {
    title?: string | null;
    keywords?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-dates".
 */
export interface EventDate {
  id: number;
  event: number | Event;
  dateFrom: string;
  dateTo: string;
  locations?: (number | Location)[] | null;
  guides?: (number | Guide)[] | null;
  airportFrom?: (number | null) | Airport;
  airportTo?: (number | null) | Airport;
  price: number;
  vat: number;
  currency: 'EUR' | 'CZK';
  capacity: number;
  minParticipants?: number | null;
  extraContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  active?: boolean | null;
  /**
   * Sum of participants in pending+confirmed+paid orders.
   */
  bookedSeats?: number | null;
  remainingSeats?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  event?: (number | null) | Event;
  program?: (number | null) | Program;
  position?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  quote: string;
  reviewerName: string;
  reviewerLocation?: string | null;
  resultLine?: string | null;
  event?: (number | null) | Event;
  program?: (number | null) | Program;
  position?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  user: number | User;
  eventDate: number | EventDate;
  participants: {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    id?: string | null;
  }[];
  participantCount: number;
  billingAddress: {
    firstName: string;
    lastName: string;
    street: string;
    city: string;
    postalCode: string;
    country: string;
    company?: {
      companyName?: string | null;
      ico?: string | null;
      dic?: string | null;
    };
  };
  unitPrice: number;
  vat: number;
  currency: 'EUR' | 'CZK';
  totalPrice: number;
  /**
   * Discount code applied at booking time (snapshot).
   */
  discountCode?: (number | null) | DiscountCode;
  /**
   * Referral source captured from URL at booking time (snapshot).
   */
  referral?: (number | null) | Referral;
  /**
   * How much the order was reduced by the applied discount, in the order currency.
   */
  discountAmount?: number | null;
  /**
   * Commission accrued for the discount-code partner, in the order currency.
   */
  discountCommission?: number | null;
  /**
   * Commission accrued for the referral partner, in the order currency.
   */
  referralCommission?: number | null;
  state: 'pending' | 'confirmed' | 'paid' | 'completed' | 'cancelled';
  /**
   * Optional note from the customer at booking time.
   */
  customerNote?: string | null;
  /**
   * Admin-only notes. Entries cannot be edited after save.
   */
  notes?:
    | {
        author: number | User;
        createdAt: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes".
 */
export interface DiscountCode {
  id: number;
  code: string;
  title: string;
  description?: string | null;
  /**
   * Whole-number percent (1–99).
   */
  discountPercent: number;
  validFrom: string;
  validUntil: string;
  commissionEmail?: string | null;
  /**
   * Commission paid out per redemption, as % of order subtotal.
   */
  commissionPercent?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals".
 */
export interface Referral {
  id: number;
  code: string;
  name: string;
  email: string;
  /**
   * Discount given to the customer using this referral (0 = commission only).
   */
  discountPercent: number;
  /**
   * Commission paid to the referrer, as % of order subtotal.
   */
  commissionPercent: number;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  seo?: {
    title?: string | null;
    keywords?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  heroImage?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | PostCategory;
  author?: string | null;
  publishedAt?: string | null;
  state: 'draft' | 'published';
  seo?: {
    title?: string | null;
    keywords?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  seo?: {
    title?: string | null;
    keywords?: string | null;
    description?: string | null;
  };
  layout?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            backgroundMedia?: (number | null) | Media;
            variant: 'overlay' | 'editorial' | 'simple';
            primaryAction?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            alignment: 'left' | 'center';
            id?: string | null;
            blockName?: string | null;
            blockType: 'section-intro';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width: 'standard' | 'wide';
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            variant: 'light' | 'dark';
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            variant: 'dark' | 'light' | 'red';
            primaryAction?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryAction?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            source: 'featured' | 'upcoming' | 'manual' | 'byProgram' | 'byLocation';
            events?: (number | Event)[] | null;
            program?: (number | null) | Program;
            location?: (number | null) | Location;
            limit: number;
            variant: 'cards' | 'compact' | 'editorial';
            id?: string | null;
            blockName?: string | null;
            blockType: 'tripGrid';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            source: 'featured' | 'all' | 'manual';
            programs?: (number | Program)[] | null;
            limit?: number | null;
            variant: 'cards' | 'compact';
            id?: string | null;
            blockName?: string | null;
            blockType: 'programGrid';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            source: 'featured' | 'all' | 'byCountry' | 'manual';
            country?: string | null;
            locations?: (number | Location)[] | null;
            limit?: number | null;
            variant: 'cards' | 'compact';
            id?: string | null;
            blockName?: string | null;
            blockType: 'locationGrid';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            source: 'team' | 'friends' | 'featured' | 'manual';
            guides?: (number | Guide)[] | null;
            limit?: number | null;
            variant: 'cards' | 'compact';
            id?: string | null;
            blockName?: string | null;
            blockType: 'guideGrid';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            source: 'latest' | 'byCategory' | 'manual';
            category?: (number | null) | PostCategory;
            posts?: (number | Post)[] | null;
            limit?: number | null;
            variant: 'cards' | 'compact';
            id?: string | null;
            blockName?: string | null;
            blockType: 'postGrid';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            source: 'upcoming' | 'byEvent' | 'manual';
            event?: (number | null) | Event;
            eventDates?: (number | EventDate)[] | null;
            limit?: number | null;
            variant: 'cards' | 'compact';
            id?: string | null;
            blockName?: string | null;
            blockType: 'calendar';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            source: 'upload' | 'externalVideo';
            media?: (number | null) | Media;
            videoUrl?: string | null;
            caption?: string | null;
            variant: 'wide' | 'contained' | 'split';
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            images: (number | Media)[];
            variant: 'grid' | 'masonry';
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            videoUrl: string;
            caption?: string | null;
            variant: 'wide' | 'contained';
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            source: 'global' | 'manual' | 'inline' | 'byEvent' | 'byProgram';
            faqs?: (number | Faq)[] | null;
            event?: (number | null) | Event;
            program?: (number | null) | Program;
            items?:
              | {
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            limit: number;
            variant: 'twoColumn' | 'singleColumn';
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            source: 'global' | 'byEvent' | 'byProgram' | 'manual';
            event?: (number | null) | Event;
            program?: (number | null) | Program;
            reviews?: (number | Review)[] | null;
            limit?: number | null;
            variant: 'cards' | 'compact';
            id?: string | null;
            blockName?: string | null;
            blockType: 'reviewGrid';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            source: 'featured' | 'all' | 'manual';
            partners?: (number | Partner)[] | null;
            limit?: number | null;
            variant: 'logos' | 'cards';
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnerStrip';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            source: 'manual' | 'currentGuide';
            guide?: (number | null) | Guide;
            variant: 'feature' | 'compact';
            id?: string | null;
            blockName?: string | null;
            blockType: 'guideProfile';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            source: 'byGuide' | 'currentGuide' | 'manual';
            guide?: (number | null) | Guide;
            events?: (number | Event)[] | null;
            limit?: number | null;
            variant: 'cards' | 'compact';
            id?: string | null;
            blockName?: string | null;
            blockType: 'guideTrips';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'difficulties';
        value: number | Difficulty;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'airports';
        value: number | Airport;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-dates';
        value: number | EventDate;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'discount-codes';
        value: number | DiscountCode;
      } | null)
    | ({
        relationTo: 'referrals';
        value: number | Referral;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  role?: T;
  addresses?:
    | T
    | {
        label?: T;
        isDefault?: T;
        firstName?: T;
        lastName?: T;
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
        company?:
          | T
          | {
              companyName?: T;
              ico?: T;
              dic?: T;
            };
        id?: T;
      };
  pendingEmail?: T;
  pendingEmailToken?: T;
  pendingEmailExpiresAt?: T;
  lastVerifyEmailSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "difficulties_select".
 */
export interface DifficultiesSelect<T extends boolean = true> {
  name?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  content?: T;
  mainPicture?: T;
  gallery?: T;
  vimeoId?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  audienceCards?:
    | T
    | {
        heading?: T;
        body?: T;
        highlighted?: T;
        id?: T;
      };
  soloNote?: T;
  redirectCallout?: T;
  curriculumPillars?:
    | T
    | {
        icon?: T;
        title?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  flow?:
    | T
    | {
        framingParagraph?: T;
        mixAndMatchBlocks?:
          | T
          | {
              title?: T;
              tagline?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
        tailoredToYou?:
          | T
          | {
              text?: T;
              id?: T;
            };
        focusTracks?:
          | T
          | {
              title?: T;
              colorTag?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  weekVariants?:
    | T
    | {
        title?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  weekRecommendation?: T;
  accommodation?:
    | T
    | {
        description?: T;
        included?:
          | T
          | {
              text?: T;
              id?: T;
            };
        foodBeverages?:
          | T
          | {
              text?: T;
              id?: T;
            };
        notIncluded?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  transport?:
    | T
    | {
        description?: T;
        airports?: T;
      };
  coachFramingParagraph?: T;
  coaches?: T;
  results?:
    | T
    | {
        text?: T;
        id?: T;
      };
  featured?: T;
  active?: T;
  state?: T;
  seo?:
    | T
    | {
        title?: T;
        keywords?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  text?: T;
  position?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  tagline?: T;
  tags?:
    | T
    | {
        text?: T;
        id?: T;
      };
  section?: T;
  photo?: T;
  content?: T;
  email?: T;
  phone?: T;
  vimeoId?: T;
  heroSub?: T;
  heroCaption?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  about?:
    | T
    | {
        headline?: T;
        facts?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        quote?: T;
        quoteAttribution?: T;
      };
  coaching?:
    | T
    | {
        intro?: T;
        pillars?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  achievements?:
    | T
    | {
        intro?: T;
        items?:
          | T
          | {
              route?: T;
              location?: T;
              grade?: T;
              id?: T;
            };
      };
  testimonial?:
    | T
    | {
        quote?: T;
        name?: T;
        tripLine?: T;
      };
  featured?: T;
  isFounder?: T;
  active?: T;
  seo?:
    | T
    | {
        title?: T;
        keywords?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  content?: T;
  address?: T;
  city?: T;
  country?: T;
  coordinates?: T;
  mainPicture?: T;
  gallery?: T;
  featured?: T;
  active?: T;
  seo?:
    | T
    | {
        title?: T;
        keywords?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "airports_select".
 */
export interface AirportsSelect<T extends boolean = true> {
  name?: T;
  iata?: T;
  country?: T;
  continent?: T;
  coordinates?: T;
  size?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  link?: T;
  description?: T;
  logo?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  content?: T;
  additionalInfo?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  mainPicture?: T;
  gallery?: T;
  vimeoId?: T;
  categories?: T;
  difficulties?: T;
  programs?: T;
  locations?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  audienceCards?:
    | T
    | {
        heading?: T;
        body?: T;
        highlighted?: T;
        id?: T;
      };
  prerequisites?:
    | T
    | {
        text?: T;
        id?: T;
      };
  equipmentIntro?: T;
  essentialEquipment?:
    | T
    | {
        icon?: T;
        name?: T;
        note?: T;
        mandatory?: T;
        id?: T;
      };
  whatYouLearn?:
    | T
    | {
        intro?: T;
        box1Heading?: T;
        box1Bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        box2Heading?: T;
        box2Bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  itinerary?:
    | T
    | {
        intro?: T;
        days?:
          | T
          | {
              dayBadge?: T;
              destinationIcon?: T;
              destinationName?: T;
              metaLine?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              highlightTags?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              schedule?:
                | T
                | {
                    time?: T;
                    activity?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
            };
      };
  accommodation?:
    | T
    | {
        description?: T;
        included?:
          | T
          | {
              text?: T;
              id?: T;
            };
        notIncluded?:
          | T
          | {
              text?: T;
              id?: T;
            };
        cuisineHighlights?: T;
      };
  transport?:
    | T
    | {
        description?: T;
        airports?: T;
      };
  coachFramingParagraph?: T;
  coaches?: T;
  coachTeamBullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  partner?: T;
  partnerEyebrow?: T;
  partnerHeadline?: T;
  partnerDescription?: T;
  partnerBenefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  demoEnabled?: T;
  demoHeading?: T;
  demoBody?: T;
  demoCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  featured?: T;
  state?: T;
  seo?:
    | T
    | {
        title?: T;
        keywords?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-dates_select".
 */
export interface EventDatesSelect<T extends boolean = true> {
  event?: T;
  dateFrom?: T;
  dateTo?: T;
  locations?: T;
  guides?: T;
  airportFrom?: T;
  airportTo?: T;
  price?: T;
  vat?: T;
  currency?: T;
  capacity?: T;
  minParticipants?: T;
  extraContent?: T;
  active?: T;
  bookedSeats?: T;
  remainingSeats?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  event?: T;
  program?: T;
  position?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  quote?: T;
  reviewerName?: T;
  reviewerLocation?: T;
  resultLine?: T;
  event?: T;
  program?: T;
  position?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  eventDate?: T;
  participants?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
        id?: T;
      };
  participantCount?: T;
  billingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
        company?:
          | T
          | {
              companyName?: T;
              ico?: T;
              dic?: T;
            };
      };
  unitPrice?: T;
  vat?: T;
  currency?: T;
  totalPrice?: T;
  discountCode?: T;
  referral?: T;
  discountAmount?: T;
  discountCommission?: T;
  referralCommission?: T;
  state?: T;
  customerNote?: T;
  notes?:
    | T
    | {
        author?: T;
        createdAt?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes_select".
 */
export interface DiscountCodesSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  description?: T;
  discountPercent?: T;
  validFrom?: T;
  validUntil?: T;
  commissionEmail?: T;
  commissionPercent?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals_select".
 */
export interface ReferralsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  email?: T;
  discountPercent?: T;
  commissionPercent?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  seo?:
    | T
    | {
        title?: T;
        keywords?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  state?: T;
  seo?:
    | T
    | {
        title?: T;
        keywords?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        keywords?: T;
        description?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              backgroundMedia?: T;
              variant?: T;
              primaryAction?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'section-intro'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    body?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              variant?: T;
              primaryAction?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryAction?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        tripGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              source?: T;
              events?: T;
              program?: T;
              location?: T;
              limit?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        programGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              source?: T;
              programs?: T;
              limit?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        locationGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              source?: T;
              country?: T;
              locations?: T;
              limit?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        guideGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              source?: T;
              guides?: T;
              limit?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        postGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              source?: T;
              category?: T;
              posts?: T;
              limit?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        calendar?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              source?: T;
              event?: T;
              eventDates?: T;
              limit?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              source?: T;
              media?: T;
              videoUrl?: T;
              caption?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              images?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              videoUrl?: T;
              caption?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              source?: T;
              faqs?: T;
              event?: T;
              program?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              limit?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        reviewGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              source?: T;
              event?: T;
              program?: T;
              reviews?: T;
              limit?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        partnerStrip?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              source?: T;
              partners?: T;
              limit?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        guideProfile?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              source?: T;
              guide?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        guideTrips?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              source?: T;
              guide?: T;
              events?: T;
              limit?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}